[[Todo-API]]
== Todo API

[[Todo-API-가입된-Todo-Team-목록]]
=== 가입된 Todo Team 목록

operation::todo-team-controller-test/get-todo-teams[snippets='http-request,request-parameters,request-headers,http-response,response-fields']

[[Todo-API-Todo-Team에-가입된-사용자-조회]]
=== Todo Team에 가입된 사용자 조회

operation::register-controller-test/get-registers[snippets='http-request,request-parameters,request-headers,http-response,response-fields']


[[Todo-API-Todo-Team-탈퇴]]
=== Todo Team 탈퇴

operation::register-controller-test/unregister-todo-team[snippets='http-request,path-parameters,request-headers,http-response']

[[Todo-API-Todo-Team-가입]]
=== Todo Team 가입

operation::register-controller-test/post-register[snippets='http-request,request-parameters,request-headers,http-response']

[[Todo-API-Todo-Team-생성]]
=== Todo Team 생성

operation::todo-team-controller-test/post-todo-team[snippets='http-request,request-part-todoTeamCreateInfo-fields,request-headers,http-response']

[[Todo-API-Todo-Team-Code-생성]]
=== Todo Team Code 생성

operation::todo-team-controller-test/get-todo-team-random-code[snippets='http-request,request-headers,http-response,response-fields']

[[Todo-API-Todo-Team-Code-조회]]
=== Todo Team Code로 Todo Team 조회

operation::todo-team-controller-test/get-todo-team-by-code[snippets='http-request,request-parameters,request-headers,http-response,response-fields']

[[Todo-API-가장-최근에-가입한-Todo-Team-조회]]
=== 가장 최근에 가입한 TodoTeam 조회

operation::todo-team-controller-test/get-todo-team-name[snippets='http-request,request-headers,http-response,response-fields']

[[Todo-API-할당-받은-Todo-조회]]
=== 할당받은 Todo 조회

operation::todo-controller-test/get-todos[snippets='http-request,path-parameters,request-parameters,request-headers,http-response,response-fields']

[[Todo-API-Todo-달성률]]
=== Todo 달성률 조회

operation::todo-controller-test/get-todo-progress[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

[[Todo-API-투두생성]]
=== Todo 생성

operation::todo-controller-test/post-todo[snippets='http-request,request-fields,request-headers,http-response']

[[Todo-API-투두-리스트-조회]]
=== Todo 카테고리 리스트 조회

operation::category-controller-test/get-category-list[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

[[Todo-API-투두-리스트-조회]]
=== Todo 투두 리스트 조회

operation::todo-controller-test/get-todo-list[snippets='http-request,path-parameters,request-headers,request-parameters,http-response,response-fields']

[[Todo-API-투두-주차-달성률-비교-조회]]
=== Todo 주차 달성률 비교

operation::todo-controller-test/get-week-progress-compare[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

[[Todo-API-투두-팀-가입-기간-조회]]
=== Todo 팀 가입 기간 조회

operation::todo-controller-test/get-register-term[snippets='http-request,path-parameters,request-headers,http-response,response-fields']