spring:
  profiles:
    include:
      - db
      - auth
      - aws

  servlet:
    multipart:
      max-file-size: 2MB

management:
  server:
    port: 8079
  endpoints:
    web:
      exposure:
        include: "prometheus"
